// <auto-generated />
using System;
using Main.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Main.Infrastructure.Migrations
{
    [DbContext(typeof(MainDataContext))]
    [Migration("20260609110101_UpdateUserFields")]
    partial class UpdateUserFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Main.Domain.Dialogs.Models.Dialog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.HasIndex("UserId");

                    b.ToTable("Dialogs", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Dialogs.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DialogId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Sender")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Translation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DialogId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Dictionary.Models.DictionaryWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DictionaryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId");

                    b.ToTable("DictionaryWords", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Dictionary.Models.UserDictionary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDictionaries", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Identity.Models.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("ExternalLogins", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Identity.Models.IdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("IdentityUsers", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Identity.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Identity.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("TestQuestionQuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TestQuestionQuestionId");

                    b.ToTable("TestQuestionQuestionOptions", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionSelectionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TestQuestionSelectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TestQuestionSelectionId");

                    b.ToTable("TestQuestionSelectionAnswers", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SessionStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TestMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.SessionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId")
                        .IsUnique();

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.ToTable("SessionItems", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("SetStatus")
                        .HasColumnType("integer");

                    b.Property<int>("TestDifficult")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sets", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.SetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("SetItems", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.TestAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TestAnswers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.TestQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExplainTerm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExplainText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TestQuestions", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Main.Domain.Tutors.Models.FavoriteTutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TutorId")
                        .IsUnique();

                    b.ToTable("FavoriteTutors", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tutors.Models.StoryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("StoryLines", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tutors.Models.TargetWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("TargetWords", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tutors.Models.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TutorRole")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic");

                    b.HasIndex("UserId");

                    b.ToTable("Tutors", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Users.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Answers.TestAnswerQuestion", b =>
                {
                    b.HasBaseType("Main.Domain.Tests.Models.TestAnswer");

                    b.Property<int>("SelectedIndex")
                        .HasColumnType("integer");

                    b.ToTable("TestAnswerQuestions", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Answers.TestAnswerSelection", b =>
                {
                    b.HasBaseType("Main.Domain.Tests.Models.TestAnswer");

                    b.Property<string>("SelectedLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable("TestAnswerSelections", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Answers.TestAnswerTrueFalse", b =>
                {
                    b.HasBaseType("Main.Domain.Tests.Models.TestAnswer");

                    b.Property<bool>("UserSaidTrue")
                        .HasColumnType("boolean");

                    b.ToTable("TestAnswerTrueFalses", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Answers.TestAnswerWritten", b =>
                {
                    b.HasBaseType("Main.Domain.Tests.Models.TestAnswer");

                    b.Property<string>("UserText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable("TestAnswerWrittens", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionQuestion", b =>
                {
                    b.HasBaseType("Main.Domain.Tests.Models.TestQuestion");

                    b.ToTable("TestQuestionQuestions", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionSelection", b =>
                {
                    b.HasBaseType("Main.Domain.Tests.Models.TestQuestion");

                    b.ToTable("TestQuestionSelections", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionTrueFalse", b =>
                {
                    b.HasBaseType("Main.Domain.Tests.Models.TestQuestion");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TermTranslation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("TestQuestionTrueFalses", (string)null);
                });

            modelBuilder.Entity("Main.Domain.Dialogs.Models.Dialog", b =>
                {
                    b.HasOne("Main.Domain.Tutors.Models.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Main.Domain.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Dialogs.Models.Message", b =>
                {
                    b.HasOne("Main.Domain.Dialogs.Models.Dialog", null)
                        .WithMany("Messages")
                        .HasForeignKey("DialogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Dictionary.Models.DictionaryWord", b =>
                {
                    b.HasOne("Main.Domain.Dictionary.Models.UserDictionary", null)
                        .WithMany("Words")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Dictionary.Models.UserDictionary", b =>
                {
                    b.HasOne("Main.Domain.Users.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Main.Domain.Dictionary.Models.UserDictionary", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionQuestionOption", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.Questions.TestQuestionQuestion", "TestQuestionQuestion")
                        .WithMany("Options")
                        .HasForeignKey("TestQuestionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestQuestionQuestion");
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionSelectionAnswer", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.Questions.TestQuestionSelection", "TestQuestionSelection")
                        .WithMany("AnswerPool")
                        .HasForeignKey("TestQuestionSelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestQuestionSelection");
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Session", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.Set", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Domain.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.SessionItem", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.TestAnswer", "Answer")
                        .WithOne()
                        .HasForeignKey("Main.Domain.Tests.Models.SessionItem", "AnswerId");

                    b.HasOne("Main.Domain.Tests.Models.TestQuestion", "Question")
                        .WithOne()
                        .HasForeignKey("Main.Domain.Tests.Models.SessionItem", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Domain.Tests.Models.Session", "Session")
                        .WithMany("SessionItems")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Set", b =>
                {
                    b.HasOne("Main.Domain.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.SetItem", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.Set", "Set")
                        .WithMany("SetItems")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Main.Domain.Tutors.Models.FavoriteTutor", b =>
                {
                    b.HasOne("Main.Domain.Tutors.Models.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Domain.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tutors.Models.StoryLine", b =>
                {
                    b.HasOne("Main.Domain.Tutors.Models.Tutor", null)
                        .WithMany("Stories")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tutors.Models.TargetWord", b =>
                {
                    b.HasOne("Main.Domain.Tutors.Models.Tutor", null)
                        .WithMany("TargetWords")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tutors.Models.Tutor", b =>
                {
                    b.HasOne("Main.Domain.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Answers.TestAnswerQuestion", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.TestAnswer", null)
                        .WithOne()
                        .HasForeignKey("Main.Domain.Tests.Models.Answers.TestAnswerQuestion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Answers.TestAnswerSelection", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.TestAnswer", null)
                        .WithOne()
                        .HasForeignKey("Main.Domain.Tests.Models.Answers.TestAnswerSelection", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Answers.TestAnswerTrueFalse", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.TestAnswer", null)
                        .WithOne()
                        .HasForeignKey("Main.Domain.Tests.Models.Answers.TestAnswerTrueFalse", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Answers.TestAnswerWritten", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.TestAnswer", null)
                        .WithOne()
                        .HasForeignKey("Main.Domain.Tests.Models.Answers.TestAnswerWritten", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionQuestion", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.TestQuestion", null)
                        .WithOne()
                        .HasForeignKey("Main.Domain.Tests.Models.Questions.TestQuestionQuestion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionSelection", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.TestQuestion", null)
                        .WithOne()
                        .HasForeignKey("Main.Domain.Tests.Models.Questions.TestQuestionSelection", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionTrueFalse", b =>
                {
                    b.HasOne("Main.Domain.Tests.Models.TestQuestion", null)
                        .WithOne()
                        .HasForeignKey("Main.Domain.Tests.Models.Questions.TestQuestionTrueFalse", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Domain.Dialogs.Models.Dialog", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Main.Domain.Dictionary.Models.UserDictionary", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Session", b =>
                {
                    b.Navigation("SessionItems");
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Set", b =>
                {
                    b.Navigation("SetItems");
                });

            modelBuilder.Entity("Main.Domain.Tutors.Models.Tutor", b =>
                {
                    b.Navigation("Stories");

                    b.Navigation("TargetWords");
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Main.Domain.Tests.Models.Questions.TestQuestionSelection", b =>
                {
                    b.Navigation("AnswerPool");
                });
#pragma warning restore 612, 618
        }
    }
}
